### ISSUE TITLE
Library not working on Kitkat devices

### ISSUE THREAD

**Issue by sandeeptengale** [tushar-acharya/PrefCompat#9]
Library not working on kitkat devices, crashes App with following error, it show when I try to initilize in Application class of App

java.lang.NoClassDefFoundError: com.tramsun.libs.prefcompat.PrefInternal$1
                                                                                at com.tramsun.libs.prefcompat.PrefInternal.<init>(PrefInternal.java:37)
                                                                                at com.tramsun.libs.prefcompat.Pref.init(Pref.java:36)
                                                                                at com.tramsun.libs.prefcompat.Pref.init(Pref.java:44)
                                                                                at com.tramsun.libs.prefcompat.Pref.init(Pref.java:48)

**Comment by tushar-acharya** [comment]
@sandeeptengale Are you sure it's not a multi-dex issue. I've tested this in Kitkat and I don't see any issues
